-- MySQL Script generated by MySQL Workbench
-- Wed May 17 17:25:39 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema emailvalidationdb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema emailvalidationdb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `emailvalidationdb` DEFAULT CHARACTER SET utf8 ;
USE `emailvalidationdb` ;

-- -----------------------------------------------------
-- Table `emailvalidationdb`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `emailvalidationdb`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(255) NOT NULL,
  `created_at` DATETIME NOT NULL,
  `updated_at` DATETIME NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
